### ISSUE TITLE
`WebSocket is already in CLOSING or CLOSED state` when calling `startSession` on disconnected conversation

### ISSUE THREAD

**Issue by AayushPaigwar** [elevenlabs/elevenlabs-examples#173]
<h3><strong>Description</strong></h3>
<p>When trying to start a conversation session using the <code inline="">@11labs/react</code> package, I receive a <code inline="">WebSocket is already in CLOSING or CLOSED state</code> error under certain conditions, especially after a previous disconnection.</p>
<hr>
<h3><strong>Steps to Reproduce</strong></h3>
<ol>
<li>
<p>Use <code inline="">useConversation()</code> from <code inline="">@11labs/react</code>.</p>
</li>
<li>
<p>Allow the session to disconnect (manually or automatically).</p>
</li>
<li>
<p>Try calling <code inline="">conversation.startSession()</code> again — for example, via a button click or <code inline="">useEffect</code>.</p>
</li>
<li>
<p>This triggers the following error:</p>
</li>
</ol>
<pre><code>connection.ts:249 WebSocket is already in CLOSING or CLOSED state.
    at sendMessage (connection.ts:249)
    at onInputWorkletMessage (index.ts:357)
</code></pre>
<hr>
<h3><strong>Expected Behavior</strong></h3>
<p><code inline="">startSession()</code> should gracefully handle reconnection scenarios. Ideally, it should:</p>
<ul>
<li>
<p>Check if the socket is in a valid state before attempting to send messages.</p>
</li>
<li>
<p>Automatically re-establish the WebSocket connection if it's closed.</p>
</li>
</ul>
<hr>
<h3><strong>Environment</strong></h3>

Key | Value
-- | --
Package | @11labs/react
Package Version | 0.1.4

**Comment by AayushPaigwar** [comment]
Hi @samtucker 
I have fixed this issue by passing the thing which were used during the creation of agent (eg. dynamic_variables)

**Comment by samtucker** [comment]
I tried that but I get: conversation.endSession() takes 0 arguments and still get the original error. 

Everything still works as expected but I just get the errors in the console only when the agent ends the call itself not when the user ends the call using the UI.

**Comment by sukritt04** [comment]
hey, hoping to get a fix for this.
